### ISSUE TITLE
Figure out how to handle opensearch-dashboards

### ISSUE THREAD

**Issue by crazymind1337** [voxpupuli/puppet-opensearch#20]
Opensearch supports dashboards. This is to find out how to make them working.

Within this module or create a new module?

**Comment by smortex** [comment]
I created a `puppet-opensearch_dashboards` repository in my personal namespace using this repo as a template:
https://github.com/smortex/puppet-opensearch_dashboards

A single-node cluster can be setup with:

```puppet
class { 'opensearch':
  settings => {
    'network.host' => '0.0.0.0',
  },
}

class { 'opensearch_dashboards':
  settings => {
    'server.host'                     => '0.0.0.0',
    'opensearch.hosts'                => [
      'https://localhost:9200',
    ],
    'opensearch.ssl.verificationMode' => 'none',
    'opensearch.username'             => 'kibanaserver',
    'opensearch.password'             => 'kibanaserver',
  },
}
```

The opensearch-dashboards project itself only has [commented-out configuration](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml), but the packages / archive have [a different config](https://github.com/opensearch-project/opensearch-build/blob/main/config/opensearch_dashboards-2.x.yml) with the above default settings. For now, they are not included but having some sane defaults might have more sense.

Can you test this and report feedback?

**Comment by smortex** [comment]
The repo was moved to the voxpupuli organization:
https://github.com/voxpupuli/puppet-opensearch_dashboards

I think we can close this issue?
