### ISSUE TITLE
If specific version specified, hold the package?

### ISSUE THREAD

**Issue by siliconalchemy** [voxpupuli/puppet-opensearch#24]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: n/a
- Ruby: n/a
- Distribution: Ubuntu (22.04)
- Module version: 0.30

## How to reproduce (e.g Puppet code you use)

If I specify a particular version (in my case this is the version that is specified/tested/developed for the latest version of Magento:

```puppet
  class { 'opensearch':
    version => '2.5.0',
  }
```

## What are you seeing

The manifest works as expected and installs 2.5.0, however because it is not the latest version, any `apt upgrade` updates the package to the latest version.  The next time puppet is run it downgrades the version, and the two flip flop each invocation.

## What behaviour did you expect instead

I would expect this module to `apt-mark hold opensearch` or something similar, to prevent changes away from the specified version.  If we specify a particular version of a component in a Configuration Management system I would expect that version to be made as consistent as possible.

**Comment by crazymind1337** [comment]
Thanks for your input. I have created a PR for that.
