### ISSUE TITLE
Install fails, Unknown function: 'stdlib::to_yaml'

### ISSUE THREAD

**Issue by d1nuc0m** [voxpupuli/puppet-opensearch#40]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.17.0 (with r10k 3.15.0)
- Ruby: 2.5.9p229
- Distribution: AlmaLinux 9.2
- Module version: v1.1.0

## How to reproduce (e.g Puppet code you use)

* Modules are installed in `/etc/puppetlabs/code/environments/devel/modules/`
    - Archive 6.1.1, Stdlib 8.5.0, Systemd 3.10.0

* Relevant code
```
include archive
include stdlib 
include opensearch
class { 'systemd':
  }
```
* On master `r10k deploy environment`
* On client `puppet agent -t -v`

## What are you seeing

Module is unable to complete install because it does not find stdlib `to_yaml` function 

## What behaviour did you expect instead

Module should find the function and install opensearch

## Output log

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'stdlib::to_yaml'. (file: /etc/puppetlabs/code/environments/devel/modules/opensearch/manifests/config.pp, line: 95, column: 27) on node {masterFQDN}
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Any additional information you'd like to impart

File `/etc/puppetlabs/code/environments/devel/modules/stdlib/lib/puppet/functions/to_yaml.rb` exists on master

**Comment by smortex** [comment]
The function is part of stdlib 9.0.0 which is the minimum required version by the module:

https://github.com/voxpupuli/puppet-opensearch/blob/3264fb0a0d0891f536aa61c6b4793fca788af1b6/metadata.json#L21-L24
